### ISSUE TITLE
[Fu Calc] ClosedRon (10Fu) added even with --tsumo

### ISSUE THREAD

**Issue by jasonhu5** [DrCheeseFace/mahc#16]
https://github.com/DrCheeseFace/mahc/blame/941133b84f0536939b36a3f1eafce27854d820bb/src/hand.rs#L131

Should the above reside in an `else` block from `if tsumo`? Like

```rust
        if tsumo {
            fu_types.push(Fu::Tsumo);
        } else {
            if !self.is_open() {
                fu_types.push(Fu::ClosedRon);
            }
        }
```

**Comment by DrCheeseFace** [comment]
```
mahc on  main [$] is 📦 v1.8.5 via 🦀 v1.82.0
❯ ./target/debug/mahc --tiles EEEw WWWw 123p 123s 11p -w 1p --tsumo

5 Han/ 50 Fu
Dealer: 12000 (4000)
Non-dealer: 8000 (2000/4000)
Yaku:
  Chantaiyao: 2
  MenzenTsumo: 1
  Yakuhai: 1
  Yakuhai: 1
Fu:
  BasePoints: 20
  Tsumo: 2
  ClosedRon: 10  <------ thats not correct
  NonSimpleClosedTriplet: 8
  NonSimpleClosedTriplet: 8
  SingleWait: 2

```

Yes youre correct, we shouldnt add `Fu::ClosedRon` if we already tsumo. We are SEVERELY lacking in fu validation tests.
good spot.

 Would you like the handle the bug as well as adding some more tests for `Hand.calculate_fu()` ?
